# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/diegosanmiguel/Documents/Personal Work/afs/private/15418/distributed-ml-mpi"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/diegosanmiguel/Documents/Personal Work/afs/private/15418/distributed-ml-mpi"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/diegosanmiguel/Documents/Personal Work/afs/private/15418/distributed-ml-mpi/CMakeFiles" "/Users/diegosanmiguel/Documents/Personal Work/afs/private/15418/distributed-ml-mpi//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/diegosanmiguel/Documents/Personal Work/afs/private/15418/distributed-ml-mpi/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dml

# Build rule for target.
dml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dml
.PHONY : dml

# fast build rule for target.
dml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/build
.PHONY : dml/fast

master_node.o: master_node.cpp.o
.PHONY : master_node.o

# target to build an object file
master_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/master_node.cpp.o
.PHONY : master_node.cpp.o

master_node.i: master_node.cpp.i
.PHONY : master_node.i

# target to preprocess a source file
master_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/master_node.cpp.i
.PHONY : master_node.cpp.i

master_node.s: master_node.cpp.s
.PHONY : master_node.s

# target to generate assembly for a file
master_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/master_node.cpp.s
.PHONY : master_node.cpp.s

serverTest.o: serverTest.cpp.o
.PHONY : serverTest.o

# target to build an object file
serverTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/serverTest.cpp.o
.PHONY : serverTest.cpp.o

serverTest.i: serverTest.cpp.i
.PHONY : serverTest.i

# target to preprocess a source file
serverTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/serverTest.cpp.i
.PHONY : serverTest.cpp.i

serverTest.s: serverTest.cpp.s
.PHONY : serverTest.s

# target to generate assembly for a file
serverTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/serverTest.cpp.s
.PHONY : serverTest.cpp.s

worker_node.o: worker_node.cpp.o
.PHONY : worker_node.o

# target to build an object file
worker_node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/worker_node.cpp.o
.PHONY : worker_node.cpp.o

worker_node.i: worker_node.cpp.i
.PHONY : worker_node.i

# target to preprocess a source file
worker_node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/worker_node.cpp.i
.PHONY : worker_node.cpp.i

worker_node.s: worker_node.cpp.s
.PHONY : worker_node.s

# target to generate assembly for a file
worker_node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dml.dir/build.make CMakeFiles/dml.dir/worker_node.cpp.s
.PHONY : worker_node.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dml"
	@echo "... master_node.o"
	@echo "... master_node.i"
	@echo "... master_node.s"
	@echo "... serverTest.o"
	@echo "... serverTest.i"
	@echo "... serverTest.s"
	@echo "... worker_node.o"
	@echo "... worker_node.i"
	@echo "... worker_node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

